accepted = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "0BSD",
    "CC0-1.0",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
    "Zlib",
    "MPL-2.0",
    "MPL-2.0+",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true

